version: 2.1

orbs:
    slack: circleci/slack@3.4.2
jobs:
    publish:
        docker:
            - image: rishabhpoddar/supertokens_website_sdk_testing
        steps:
            - checkout
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - run:
                  name: Publish
                  command: |
                      cd .circleci
                      ./publish.sh
            - slack/status

workflows:
    version: 2
    tagged-build:
        jobs:
            - publish:
                  context:
                      - slack-notification
                  filters:
                      tags:
                          only: /v[0-9]+(\.[0-9]+)*/
                      branches:
                          ignore: /.*/
